{"uuid":"5aff41f1-c134-40d5-9e31-974502497860","historyId":"38363fa27659c099fba3ac94b8e16419","fullName":"com.testng.features.Expected_Exception.calc","labels":[{"name":"package","value":"com.testng.features.Expected_Exception"},{"name":"testClass","value":"com.testng.features.Expected_Exception"},{"name":"testMethod","value":"calc"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.testng.features.Expected_Exception"},{"name":"host","value":"DESKTOP-GBUCELS"},{"name":"thread","value":"5660@DESKTOP-GBUCELS.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"calc","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nMethod Expected_Exception.calc()[pri:0, instance:com.testng.features.Expected_Exception@15c43bd9] should have thrown an exception of type class java.lang.NullPointerException","trace":"org.testng.TestException: \nMethod Expected_Exception.calc()[pri:0, instance:com.testng.features.Expected_Exception@15c43bd9] should have thrown an exception of type class java.lang.NullPointerException\r\n\tat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)\r\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(Unknown Source)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1664556955215,"stop":1664556955246}